### ISSUE TITLE
我只能文字描述问题了

### ISSUE THREAD

**Issue by saeson001** [miaomiaosoft/TaskbarX#1]
1、流量不显示，不论是上行还是下行，网卡是82579V
2、主硬盘显示 不准确，我有4个硬盘，120G的SSD是系统盘，软件显示3T的HDD才是主硬盘，怎么分的？
3、资讯能不能做个开关？我不想看资讯，但我在设置里只找到了语音播报的开关
4、IP也不显示，原因未知，空的。

**Comment by miaomiaosoft** [comment]
1. 流量的NETID需要自己改，比如WIN7大概是11，不是11的话只能自己尝试12，13等等直到数值显示
2. 我只负责任务栏部分，硬件检测我不管的，本来是应该屏蔽掉的，那部分不是我写的
3. 开关还在设想该怎么弄比较好
4. IP空的？不应该！截图我看看

**Comment by saeson001** [comment]
IP那我以为是显示我自己的外网IP，原来只是PING指定IP或网址的延时，这个是有显示的

流量 ID找到了，但有个问题，测试的时候，我只能在INI里改，然后退出软件再开，检查是否成功，这样的话，退出后在任务栏，软件原来占的位置经常不会自动刷新，原来占了多少，退出后还占多少，再打开程序的软件又重新占用新的位置。有时候还会错位

![image](https://user-images.githubusercontent.com/53417010/75368981-918b0a00-58fd-11ea-9f59-ffe8d51960dc.png)

**Comment by saeson001** [comment]
上面的图是右下角时钟和托盘的位置被占用了

**Comment by miaomiaosoft** [comment]
重启下资源管理器
或者 
退出程序后随便点两下托盘前面那个展开按钮，然后再启动
