### ISSUE TITLE
NvContral.dll 没过ESET

### ISSUE THREAD

**Issue by 2220209876** [miaomiaosoft/TaskbarX#3]
NvContral.dll 没过ESET

![2020-04-24_15-28-11](https://user-images.githubusercontent.com/7346652/80186396-807e2100-8640-11ea-8bfb-2080a9bce7ff.png)

**Comment by 2220209876** [comment]
NvContral.dll已白名单但是还会报错，点击确定程序会自动退出
![2020-04-24_15-36-32](https://user-images.githubusercontent.com/7346652/80187006-80325580-8641-11ea-876a-6ac34a62d64b.png)

**Comment by miaomiaosoft** [comment]
DLL是安全的，但这DLL是几年前的了，可能不支持某些新的显卡，我也没办法

**Comment by 2220209876** [comment]
> DLL是安全的，但DLL是几年前的了，可能不支持某些新的闪光灯，我也没办法
显卡是A卡

**Comment by miaomiaosoft** [comment]
A卡那更不支持了，我自己是N卡，所以只有N卡部分的代码

**Comment by 2220209876** [comment]
> A卡那更不支持了，我自己是N卡，所以只有N卡部分的代码

如果是A卡用户，下个版本可以把显卡相关的功能关闭，其他功能也不能正常使用吗？

**Comment by miaomiaosoft** [comment]
可以，但也要考虑上下对称问题，关了那CPU下面那行可就空了
正在考虑更好的方案

**Comment by 2220209876** [comment]
> 可以，但也要考虑上下对称问题，关了那CPU下面那行可就空了
> 正在考虑更好的方案

换成内存占用，或者用户自定义签名
